# Alacritty Config

window:
  opacity: 0.8
  title: Alacritty
  dynamic_title: false

font:
  normal:
    family: Hack Nerd Font Mono
    style: Regular

  bold:
    family: Hack Nerd Font Mono
    style: Bold

  italic:
    family: Hack Nerd Font Mono
    style: Italic

  bold_italic:
    family: Hack Nerd Font Mono
    style: Bold Italic
  size: 13

shell:
  program: /bin/fish
  #args:
    #- --login

