# Alacritty Config

window:
  opacity: 0.7
  title: Alacritty
  dynamic_title: false

font:
  normal:
    family: Droid Sans Mono Nerd Font 

  size: 13.0

  offset:
    y: 1

cursor:
  style:
    blinking: On

  blink_interval: 500
  blink_timeout: 0
  thickness: 0.15

shell:
  program: /bin/fish
  #args:
    #- --login

